"""
Builds the skill book icons for QoL Compendium.

The coffee set from An Exhilaratingly Organized Literature Mod covers eleven skills, all
of them build 41 era. Build 42 has twenty four, so thirteen families are missing outright
and Blacksmith is referenced by the original's own lua with no texture behind it.

Drawing thirteen more by hand was never necessary. Within one volume every family in the
set is the same sprite in a different colour: of 1024 pixels only 457 differ between
families, and the page block, the volume numeral and the outline are identical everywhere.
So the missing families are generated by recolouring, which matches the existing art
exactly rather than approximately.

Also writes a fully transparent mask. Ten of the build 42 skill books carry
IconColorMask = Book_Generic_Mask, and UIElement.DrawItemIcon draws that mask over the
icon tinted with the item's colour. Pointing those items at a transparent mask instead is
what stops vanilla's tint landing on top of our art. It cannot simply be blanked:
InventoryItem.setTextureColorMask falls back to the question mark texture when the name
does not resolve.

Reads from other-mods/, which is deliberately not in the repository, so this is here for
reproducibility rather than as part of a build. The icons it writes are committed.

Usage:  python tools/generate_book_icons.py
"""
import colorsys
import os
import shutil

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'other-mods', 'An Exhilaratingly Organized Literature Mod',
                   'mods', 'ListSortOGSN_rice', 'media', 'textures')
DEST = os.path.join(ROOT, 'QoLCompendium', 'Contents', 'mods', 'QoLCompendium',
                    'common', 'media', 'textures')

PREFIX = 'QolcBook'
VOLUMES = (1, 2, 3, 4, 5)

# The family the recolour is measured from, and the dominant colour of its cover. Any of
# the eleven would do, they are the same sprite.
BASE = 'Carpentry'
BASE_SAT = 0.44
BASE_VAL = 0.52

# Families the set already covers, copied across untouched.
SHIPPED = ('Carpentry', 'Cooking', 'Electrician', 'Farming', 'FirstAid', 'Fishing',
           'Foraging', 'Mechanic', 'MetalWelding', 'Tailoring', 'Trapping')

# Hue in degrees, saturation and value of the cover, for the families build 42 added.
#
# Chosen against the eleven above rather than off a colour wheel, because those already
# crowd the browns at 30 to 40 and the blues at 193 to 258. Where hue alone cannot
# separate two families they are separated by brightness instead, which is how the
# original set already tells Mechanic, Tailoring and Trapping apart.
NEW = {
    'Pottery':       (12, 0.62, 0.60),
    'FlintKnapping': (24, 0.22, 0.66),
    'Reloading':     (50, 0.72, 0.38),
    'Masonry':       (70, 0.48, 0.72),
    'Husbandry':     (108, 0.45, 0.58),
    'Maintenance':   (132, 0.36, 0.42),
    'Glassmaking':   (178, 0.32, 0.82),
    'Blacksmith':    (210, 0.22, 0.28),
    'LongBlade':     (238, 0.58, 0.38),
    'Carving':       (285, 0.32, 0.68),
    'Aiming':        (312, 0.48, 0.55),
    'Butchering':    (340, 0.58, 0.44),
    'Tracking':      (358, 0.30, 0.32),
}


def source(family, volume):
    return os.path.join(SRC, 'Item_book_rice_%s%d.png' % (family, volume))


def cover_mask(volume):
    """Which pixels belong to the cover, worked out by diffing families rather than by
    guessing at a colour range. Anything identical across all four is page, numeral or
    outline and must come through untouched."""
    samples = [list(Image.open(source(f, volume)).convert('RGBA').get_flattened_data())
               for f in ('Carpentry', 'Cooking', 'Foraging', 'Fishing')]
    return [len(set(px)) > 1 for px in zip(*samples)]


def recolour(volume, hue, sat, val):
    src = Image.open(source(BASE, volume)).convert('RGBA')
    mask = cover_mask(volume)
    pixels = []

    for is_cover, px in zip(mask, src.get_flattened_data()):
        if not is_cover or px[3] == 0:
            pixels.append(px)
            continue

        # Saturation and value are scaled rather than replaced, so the shading ramp the
        # original artist drew survives the change of hue
        _, ps, pv = colorsys.rgb_to_hsv(*[c / 255.0 for c in px[:3]])
        r, g, b = colorsys.hsv_to_rgb(hue / 360.0,
                                      min(1.0, ps * sat / BASE_SAT),
                                      min(1.0, pv * val / BASE_VAL))
        pixels.append((int(r * 255), int(g * 255), int(b * 255), px[3]))

    out = Image.new('RGBA', src.size)
    out.putdata(pixels)
    return out


def main():
    if not os.path.isdir(SRC):
        raise SystemExit('source icons not found, expected them at %s' % SRC)
    os.makedirs(DEST, exist_ok=True)

    copied = generated = 0

    for family in SHIPPED:
        for volume in VOLUMES:
            shutil.copyfile(source(family, volume),
                            os.path.join(DEST, 'Item_%s%s%d.png' % (PREFIX, family, volume)))
            copied += 1

    for family, (hue, sat, val) in sorted(NEW.items()):
        for volume in VOLUMES:
            recolour(volume, hue, sat, val).save(
                os.path.join(DEST, 'Item_%s%s%d.png' % (PREFIX, family, volume)))
            generated += 1

    # Draws nothing, which is the point. See the note at the top about the tint.
    size = Image.open(source(BASE, 1)).size
    Image.new('RGBA', size, (0, 0, 0, 0)).save(
        os.path.join(DEST, 'Item_%sNoTint.png' % PREFIX))

    print('copied %d, generated %d, %d families in total'
          % (copied, generated, len(SHIPPED) + len(NEW)))


if __name__ == '__main__':
    main()
